linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - misspell
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  gosec:
    excludes:
      - G204 # subprocess launched with variable — needed for git commands

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
